# Generated by Django 4.2.9 on 2024-09-20 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorstoken',
            name='first_color',
            field=models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('green', 'Green')], max_length=256),
        ),
        migrations.AlterField(
            model_name='colorstoken',
            name='second_color',
            field=models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('green', 'Green')], max_length=256),
        ),
    ]
