# Generated by Django 4.2.9 on 2024-09-20 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oat', '0002_alter_colorstoken_first_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorstoken',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
