# Generated by Django 4.2.9 on 2024-09-21 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oat', '0003_colorstoken_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorstoken',
            name='first_color',
            field=models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('pink', 'Pink'), ('purple', 'Purple'), ('yellow', 'Yellow'), ('black', 'Black')], max_length=256),
        ),
        migrations.AlterField(
            model_name='colorstoken',
            name='second_color',
            field=models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('pink', 'Pink'), ('purple', 'Purple'), ('yellow', 'Yellow'), ('black', 'Black')], max_length=256),
        ),
    ]
